const dotenv = require('dotenv')
dotenv.config({ path: `${process.cwd()}/.env` })

const API_PORT = process.env.API_PORT
const API_HOST = process.env.API_HOST
const API_PATH = process.env.API_PATH
const DEVELOP_MODE = process.env.DEVELOP_MODE
const API_UPLOAD_PATH = process.env.API_UPLOAD_PATH
const API_UPLOAD_INCLUDE_PATHS = process.env.API_UPLOAD_INCLUDE_PATHS
const CV_DATABASE_NAME = process.env.CV_DATABASE_NAME
const CV_DATABASE_HOST = process.env.CV_DATABASE_HOST
const CV_DATABASE_PORT = process.env.CV_DATABASE_PORT
const CV_DATABASE_USERNAME = process.env.CV_DATABASE_USERNAME
const CV_DATABASE_PASSWORD = process.env.CV_DATABASE_PASSWORD
const CV_DATABASE_AUTO_CREATE = process.env.CV_DATABASE_AUTO_CREATE
const CV_MONGODB_URI = process.env.CV_MONGODB_URI
const CV_DATABASE_REPLICA_SET = process.env.CV_DATABASE_REPLICA_SET
const API_FILE_FIELDS = process.env.API_FILE_FIELDS
const AUTH_SERVICE_URL = process.env.AUTH_SERVICE_URL
const METRICS_ROUTE = process.env.METRICS_ROUTE
const METRICS_PREFIX = process.env.METRICS_PREFIX
const CORS_ALLOWED_ORIGINS = process.env.CORS_ALLOWED_ORIGINS
const API_UPLOAD_MAX_FILE_SIZE = process.env.API_UPLOAD_MAX_FILE_SIZE
const API_UPLOAD_ALLOWED_FORMATS = process.env.API_UPLOAD_ALLOWED_FORMATS
const METRICS_TOKEN = process.env.METRICS_TOKEN
const RATE_LIMIT_WINDOW_MS = process.env.RATE_LIMIT_WINDOW_MS
const RATE_LIMIT_MAX = process.env.RATE_LIMIT_MAX
const SECURITY_CORP_POLICY = process.env.SECURITY_CORP_POLICY

module.exports = {
	API_PORT,
	API_HOST,
	API_PATH,
	DEVELOP_MODE,
	API_UPLOAD_PATH,
	API_UPLOAD_INCLUDE_PATHS,
	CV_DATABASE_NAME,
	CV_DATABASE_HOST,
	CV_DATABASE_PORT,
	CV_DATABASE_USERNAME,
	CV_DATABASE_PASSWORD,
	CV_DATABASE_AUTO_CREATE,
	CV_MONGODB_URI,
	CV_DATABASE_REPLICA_SET,
	API_FILE_FIELDS,
	AUTH_SERVICE_URL,
	METRICS_ROUTE,
	METRICS_PREFIX,
	CORS_ALLOWED_ORIGINS,
	API_UPLOAD_MAX_FILE_SIZE,
	API_UPLOAD_ALLOWED_FORMATS,
	METRICS_TOKEN,
	RATE_LIMIT_WINDOW_MS,
	RATE_LIMIT_MAX,
	SECURITY_CORP_POLICY
}